export interface Student {
  id: string;
  rollNumber: string;
  name: string;
  avatarUrl: string;
  status: 'Present' | 'Absent';
  branch: 'B.Tech CSE' | 'CSE(DS)';
  location?: string;
  locationWarning?: boolean;
}

export const COLLEGE_LOCATION = {
  latitude: 28.7041, // Rohini, Delhi (simulating a college location)
  longitude: 77.1025,
};

export const ALL_BRANCHES = [
  { value: 'B.Tech CSE', label: 'B.Tech CSE' },
  { value: 'CSE(DS)', label: 'CSE (Data Science)' },
];

const cseStudents: Omit<Student, 'id' | 'avatarUrl' | 'status'>[] = [
    { name: 'AKUNUR SAI BRINDA', rollNumber: '23XV1M0501', branch: 'B.Tech CSE' },
    { name: 'AMARAM SINDHU REDDY', rollNumber: '23XV1M0502', branch: 'B.Tech CSE' },
    { name: 'A. AMRUTHA VARSHINI', rollNumber: '23XV1M0503', branch: 'B.Tech CSE' },
    { name: 'APPANA HEMANTH', rollNumber: '23XV1M0504', branch: 'B.Tech CSE' },
    { name: 'A V S MEGHANA', rollNumber: '23XV1M0505', branch: 'B.Tech CSE' },
    { name: 'B HAMSA LEKHA', rollNumber: '23XV1M0506', branch: 'B.Tech CSE' },
    { name: 'BHAVANA KODALI', rollNumber: '23XV1M0507', branch: 'B.Tech CSE' },
    { name: 'BILAL AHMED', rollNumber: '23XV1M0508', branch: 'B.Tech CSE' },
    { name: 'CHINMAYI BACHU', rollNumber: '23XV1M0509', branch: 'B.Tech CSE' },
    { name: 'C. SAMIHA KRISHNA', rollNumber: '23XV1M0510', branch: 'B.Tech CSE' },
    { name: 'D. NRUSIMHA SAI TEJA', rollNumber: '23XV1M0511', branch: 'B.Tech CSE' },
    { name: 'DODDAPUNENI VINAY', rollNumber: '23XV1M0512', branch: 'B.Tech CSE' },
    { name: 'GANTI VAISHNAVI', rollNumber: '23XV1M0513', branch: 'B.Tech CSE' },
    { name: 'GOLLAPALLY SHIVARAJ', rollNumber: '23XV1M0514', branch: 'B.Tech CSE' },
    { name: 'G ASHRITH REDDY', rollNumber: '23XV1M0515', branch: 'B.Tech CSE' },
    { name: 'GUNDELLI NAVTEJ', rollNumber: '23XV1M0516', branch: 'B.Tech CSE' },
    { name: 'HARINEESHA NUTAKKI', rollNumber: '23XV1M0517', branch: 'B.Tech CSE' },
    { name: 'ISHWAR MAMIDI', rollNumber: '23XV1M0518', branch: 'B.Tech CSE' },
    { name: 'JAKKA JISHNU SAI', rollNumber: '23XV1M0519', branch: 'B.Tech CSE' },
    { name: 'KAMBAMPATI ANIRUDH', rollNumber: '23XV1M0520', branch: 'B.Tech CSE' },
    { name: 'K. SAI ASWINI BHAAVYA', rollNumber: '23XV1M0521', branch: 'B.Tech CSE' },
    { name: 'KOTA SREEJA REDDY', rollNumber: '23XV1M0522', branch: 'B.Tech CSE' },
    { name: 'T SHASHIDHAR YADAV', rollNumber: '23XV1M0523', branch: 'B.Tech CSE' },
    { name: 'K. KRISHNA CHARITHA', rollNumber: '23XV1M0524', branch: 'B.Tech CSE' },
    { name: 'KRUTHI SEETHA', rollNumber: '23XV1M0525', branch: 'B.Tech CSE' },
    { name: 'PRANAV MANDA', rollNumber: '23XV1M0526', branch: 'B.Tech CSE' },
    { name: 'PATWARI HARSHITHA', rollNumber: '23XV1M0527', branch: 'B.Tech CSE' },
    { name: 'P. MOHIT N. V. ADITYA', rollNumber: '23XV1M0528', branch: 'B.Tech CSE' },
    { name: 'S. BHAVAJNYA', rollNumber: '23XV1M0529', branch: 'B.Tech CSE' },
    { name: 'UPPADA ENOS', rollNumber: '23XV1M0530', branch: 'B.Tech CSE' },
    { name: 'VATTIKONDA TANVI', rollNumber: '23XV1M0531', branch: 'B.Tech CSE' },
    { name: 'V. NACHIKETH REDDY', rollNumber: '23XV1M0532', branch: 'B.Tech CSE' },
    { name: 'K. YASHOVARDHAN REDDY', rollNumber: '23XV1M0533', branch: 'B.Tech CSE' },
    { name: 'ZOYA FATIMA', rollNumber: '23XV1M0534', branch: 'B.Tech CSE' },
    { name: 'G. VAMSHI KRISHNA', rollNumber: '23XV1M0535', branch: 'B.Tech CSE' },
    { name: 'M. VENKATA SAI MEERAJ', rollNumber: '23XV1M0536', branch: 'B.Tech CSE' },
    { name: 'T. NAGA YASWITHA', rollNumber: '23XV1M0537', branch: 'B.Tech CSE' },
    { name: 'AVALA CHARAN', rollNumber: '23XV1M0538', branch: 'B.Tech CSE' },
    { name: 'M. JOSEPH REDDY', rollNumber: '23XV1M0539', branch: 'B.Tech CSE' },
    { name: 'ADA ANURAG REDDY', rollNumber: '23XV1M0540', branch: 'B.Tech CSE' },
    { name: 'KOMATI YASHVITHA', rollNumber: '23XV1M0541', branch: 'B.Tech CSE' },
    { name: 'J SAI MOKSHAGNA', rollNumber: '23XV1M0542', branch: 'B.Tech CSE' },
    { name: 'KRUPALI RAO KATARI', rollNumber: '23XV1M0543', branch: 'B.Tech CSE' },
    { name: 'BHARATULA SAI LAHARI', rollNumber: '23XV1M0544', branch: 'B.Tech CSE' },
    { name: 'THAPASVI POOGURI', rollNumber: '23XV1M0545', branch: 'B.Tech CSE' },
    { name: 'KASIREDDY RUDRA VAMSI', rollNumber: '23XV1M0546', branch: 'B.Tech CSE' },
    { name: 'SHAIK TASNEEM', rollNumber: '23XV1M0547', branch: 'B.Tech CSE' },
    { name: 'N. HARSHA VARDHAN RAJU', rollNumber: '23XV1M0548', branch: 'B.Tech CSE' },
    { name: 'KONDAPARTHI VARUN', rollNumber: '23XV1M0549', branch: 'B.Tech CSE' },
    { name: 'SAI RAKESH SAI SRINIVASAN', rollNumber: '23XV1M0550', branch: 'B.Tech CSE' },
    { name: 'ATMAKURI AKSHATH', rollNumber: '23XV1M0551', branch: 'B.Tech CSE' },
    { name: 'RAMALA SIDDU VINAY', rollNumber: '23XV1M0552', branch: 'B.Tech CSE' },
    { name: 'PREM SAI BAWGI', rollNumber: '23XV1M0553', branch: 'B.Tech CSE' },
    { name: 'VEMULAPALLI BHAVANA', rollNumber: '23XV1M0554', branch: 'B.Tech CSE' },
    { name: 'BANDA KARTHIK YADAV', rollNumber: '23XV1M0555', branch: 'B.Tech CSE' },
    { name: 'G. SHAURYA VARMA', rollNumber: '23XV1M0556', branch: 'B.Tech CSE' },
    { name: 'KEESARA MUKESH REDDY', rollNumber: '23XV1M0558', branch: 'B.Tech CSE' },
];

const dsStudents: Omit<Student, 'id' | 'avatarUrl' | 'status'>[] = [
    { name: 'ADDANKI HARSHITHA', rollNumber: '23XV1M6701', branch: 'CSE(DS)' },
    { name: 'AGALDUVITY ROHIT', rollNumber: '23XV1M6702', branch: 'CSE(DS)' },
    { name: 'ANANTHULA AKHIL KUMAR', rollNumber: '23XV1M6703', branch: 'CSE(DS)' },
    { name: 'ARUDRA JHRIVED SAI', rollNumber: '23XV1M6704', branch: 'CSE(DS)' },
    { name: 'ASMITA SAMAYAM', rollNumber: '23XV1M6705', branch: 'CSE(DS)' },
    { name: 'BOLLADI YASHWANTH REDDY', rollNumber: '23XV1M6706', branch: 'CSE(DS)' },
    { name: 'CHANDA PRANAV', rollNumber: '23XV1M6707', branch: 'CSE(DS)' },
    { name: 'CHIGURU VARUN', rollNumber: '23XV1M6708', branch: 'CSE(DS)' },
    { name: 'DUDDU HARSHAVARDHAN', rollNumber: '23XV1M6709', branch: 'CSE(DS)' },
    { name: 'GADDE YAKSHA', rollNumber: '23XV1M6710', branch: 'CSE(DS)' },
    { name: 'G. SAI JAIWANTU', rollNumber: '23XV1M6711', branch: 'CSE(DS)' },
    { name: 'G. PRABHAS ARYAN', rollNumber: '23XV1M6712', branch: 'CSE(DS)' },
    { name: 'GORIJAVOLU RAMPHANI PRASAD', rollNumber: '23XV1M6713', branch: 'CSE(DS)' },
    { name: 'GVS LALITHA SIVA PRIYA', rollNumber: '23XV1M6714', branch: 'CSE(DS)' },
    { name: 'JERRIPOTULA DHARAN', rollNumber: '23XV1M6715', branch: 'CSE(DS)' },
    { name: 'HITESH REDDY. K', rollNumber: '23XV1M6716', branch: 'CSE(DS)' },
    { name: 'KLV CHAITANYA', rollNumber: '23XV1M6717', branch: 'CSE(DS)' },
    { name: 'K. LAKSHMI VYSHNAVI', rollNumber: '23XV1M6718', branch: 'CSE(DS)' },
    { name: 'KATTA YOGITH REDDY', rollNumber: '23XV1M6719', branch: 'CSE(DS)' },
    { name: 'KV SOURAV SOHIL', rollNumber: '23XV1M6720', branch: 'CSE(DS)' },
    { name: 'KRAPA HARSHA VARDHAN', rollNumber: '23XV1M6721', branch: 'CSE(DS)' },
    { name: 'KUNTLA SRI SAHITHI', rollNumber: '23XV1M6722', branch: 'CSE(DS)' },
    { name: 'LALITHADITHYA REDDY', rollNumber: '23XV1M6723', branch: 'CSE(DS)' },
    { name: 'MANASWINI KORATAGIRI', rollNumber: '23XV1M6724', branch: 'CSE(DS)' },
    { name: 'M. GAYATRI REDDY', rollNumber: '23XV1M6725', branch: 'CSE(DS)' },
    { name: 'DINESH KUMAR MARANANI', rollNumber: '23XV1M6726', branch: 'CSE(DS)' },
    { name: 'MOHAMMED NAHID HASAN', rollNumber: '23XV1M6727', branch: 'CSE(DS)' },
    { name: 'M. VENKATNATH REDDY', rollNumber: '23XV1M6728', branch: 'CSE(DS)' },
    { name: 'M. SAI GAGANA LAASYA', rollNumber: '23XV1M6729', branch: 'CSE(DS)' },
    { name: 'MUPPIDI SAIKA BRINDA', rollNumber: '23XV1M6730', branch: 'CSE(DS)' },
    { name: 'PASUMARTHI VAIBHAV', rollNumber: '23XV1M6731', branch: 'CSE(DS)' },
    { name: 'RISHIKA CHERUPELLY', rollNumber: '23XV1M6732', branch: 'CSE(DS)' },
    { name: 'S ROHAN SREEHARSHA', rollNumber: '23XV1M6733', branch: 'CSE(DS)' },
    { name: 'M SAATHVIK VARMA', rollNumber: '23XV1M6734', branch: 'CSE(DS)' },
    { name: 'SHAIK TAUFEEQ AHMAD', rollNumber: '23XV1M6735', branch: 'CSE(DS)' },
    { name: 'SHRIHARI BHIDE', rollNumber: '23XV1M6736', branch: 'CSE(DS)' },
    { name: 'S KRISHNA KEERTHANA', rollNumber: '23XV1M6737', branch: 'CSE(DS)' },
    { name: 'SOWMYA ADLURI', rollNumber: '23XV1M6738', branch: 'CSE(DS)' },
    { name: 'SRESTA BHUPATHI', rollNumber: '23XV1M6739', branch: 'CSE(DS)' },
    { name: 'SUPRAJA ANANTHULA', rollNumber: '23XV1M6740', branch: 'CSE(DS)' },
    { name: 'K CHAKRADHAR REDDY', rollNumber: '23XV1M6741', branch: 'CSE(DS)' },
    { name: 'T. DEERAJ KRISHNA', rollNumber: '23XV1M6742', branch: 'CSE(DS)' },
    { name: 'TANMAY GUNNAM', rollNumber: '23XV1M6743', branch: 'CSE(DS)' },
    { name: 'TATA SUCHETH', rollNumber: '23XV1M6744', branch: 'CSE(DS)' },
    { name: 'TERA DAIVA PREM', rollNumber: '23XV1M6745', branch: 'CSE(DS)' },
    { name: 'TUMMA NIKHIL KUMAR', rollNumber: '23XV1M6746', branch: 'CSE(DS)' },
    { name: 'V ARUN RAJ GOUD', rollNumber: '23XV1M6747', branch: 'CSE(DS)' },
    { name: 'V VAMSHI KRISHNA BHARADWAJ', rollNumber: '23XV1M6748', branch: 'CSE(DS)' },
    { name: 'VUDDANTI HIMA VARENYA', rollNumber: '23XV1M6749', branch: 'CSE(DS)' },
    { name: 'YAMINI LOKESH', rollNumber: '23XV1M6750', branch: 'CSE(DS)' },
    { name: 'S. ABHISHEK NAIDU', rollNumber: '23XV1M6751', branch: 'CSE(DS)' },
    { name: 'CH. SAILAKSHMI HARINI', rollNumber: '23XV1M6752', branch: 'CSE(DS)' },
    { name: 'SURAPUREDDY RAHUL', rollNumber: '23XV1M6753', branch: 'CSE(DS)' },
    { name: 'K VENKATA PALLAVI', rollNumber: '23XV1M6754', branch: 'CSE(DS)' },
    { name: 'BOLISETTY SUBBARAYUDU', rollNumber: '23XV1M6755', branch: 'CSE(DS)' },
    { name: 'C SASANK VARDHAN', rollNumber: '23XV1M6756', branch: 'CSE(DS)' },
    { name: 'K LAKSHMI ABHINAV SIVESH', rollNumber: '23XV1M6757', branch: 'CSE(DS)' },
    { name: 'SIBANI TIWARI', rollNumber: '23XV1M6758', branch: 'CSE(DS)' },
    { name: 'VENUMUDDALA RISHI', rollNumber: '23XV1M6759', branch: 'CSE(DS)' },
    { name: 'TADEPALLI VENKATESH', rollNumber: '23XV1M6760', branch: 'CSE(DS)' },
];


export const mockStudentData: Student[] = [...cseStudents, ...dsStudents].map((student, index) => ({
  ...student,
  id: `${index + 1}`,
  avatarUrl: `https://placehold.co/400x400.png`,
  status: 'Absent',
}));
